name: Image size

on:
    push:
        branches:
        - master
        paths:
        - src/*

jobs:
    deploy:
        name: Deploy job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v1

            - name: Build Docker image
              run: |
                docker build . --tag server/image:${{ github.sha }}

            - name: Check size of image    
              run: |
                docker images server/image

            - name: Test running of container
              run: |
                docker run --name server server/image:${{ github.sha }}

            - name: Stop running container
              run: |
                docker kill server